### ISSUE TITLE
Fix feature list generation

### ISSUE THREAD

**Issue by cherylking** [OpenLiberty/liberty-language-server#125]
This code does not seem correct. Any generated file should be in the `.libertyls` folder under the build/target folder. Second, I'm not sure what purpose the empty featurelist.xml serves. Either there should be no default feature list, or use a generated one.

https://github.com/OpenLiberty/liberty-language-server/blob/bb3a4dc34250a900fbd55cef434fa5277a707f0d/lemminx-liberty/src/main/java/io/openliberty/tools/langserver/lemminx/services/FeatureService.java#L213

**Comment by cherylking** [comment]
Additional note, I am not getting any featurelist.xml copied/generated in that location when I run our integration tests for lemminx-liberty.

<img width="425" alt="Screen Shot 2022-10-14 at 11 52 52 AM" src="https://user-images.githubusercontent.com/29436451/195900557-c0f05cee-dadf-4948-a02d-0c6bad789497.png">

**Comment by kathrynkodama** [comment]
My understanding of the referenced method: https://github.com/OpenLiberty/liberty-language-server/blob/43785209b469e98287f3cacc21021f7513230458/lemminx-liberty/src/main/java/io/openliberty/tools/langserver/lemminx/services/FeatureService.java#L187-L251 is:
1. Creates an empty featurelist.xml file in the lemminx cache (uses the empty one from the GH repo)
2. Uses the `ws-featurelist.jar` to generate a list of installed features
I think the intent of the empty featurelist.xml file was to create the file first in the lemminx cache and then overwrite it with the `ws-featurelist.jar` generated featurelist.xml file.

Then, it may not be appearing when the integration tests run because I thought we only use the installed feature list if we cannot fetch the features corresponding to the Liberty version first from Maven Central: https://github.com/OpenLiberty/liberty-language-server/blob/43785209b469e98287f3cacc21021f7513230458/lemminx-liberty/src/main/java/io/openliberty/tools/langserver/lemminx/services/FeatureService.java#L151-L169

This was also before the introduction of the .libertyls folder, so I agree that maybe it makes more sense to place the featurelist.xml file there. In which case we may not need the empty list to be created first.
