### ISSUE TITLE
For project using Gradle and Maven both, the Gradle install is detected as newer even with the Maven project has been more recently used.

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/liberty-language-server#188]
If I do:
> $ gradle libertyDev

then 
> $ mvn liberty:dev

in the same project, the LCLS logic is going to have to guess which install the server.xml is associated with.

It looks like [here](https://github.com/OpenLiberty/liberty-language-server/blob/dbf22fa124ff83d9cb0634070273345221b5ba0e/lemminx-liberty/src/main/java/io/openliberty/tools/langserver/lemminx/util/LibertyUtils.java#L120-L138) we attempt to use the lastModified timestamp, e.g. for the 'openliberty.properties' file.

However, I'm just observing on my local Windows install that in this case, the Gradle install always shows a newer timestamp for this file, even the Maven install was done more recently.   The timestamp seems to be preserved in the Maven artifact archive, whereas in the Gradle case it is set during install when the file is copied into place.

E.g. I have this although I ran the `mvn liberty:dev` more recently than the gradle one, for OL 23.0.0.7:

> -rw-r--r-- 1 GMX+854188897 4096 922 Aug  1 14:11 ./build/wlp/lib/versions/openliberty.properties
> -rw-r--r-- 1 GMX+854188897 4096 922 Jul 10 15:05 ./target/liberty/wlp/lib/versions/openliberty.properties

**Comment by scottkurz** [comment]
Not sure if this is a good time to ask the question:  but I wonder how a path like this works if the install dir is external to the build/target dir altogether?    (Don't feel obliged to answer if it's a totally separate path).

**Comment by cherylking** [comment]
So my thoughts on this are we could traverse the path up to the dir containing `wlp` to compare timestamps. 

As for an external install dir, we do not currently handle that at all. It would use the default server schema because the code would not find a `ws-schemagen.jar` in the workspace. This is a totally separate path that will potentially involve needing to build the project (or invoke some setup goal/task at a minimum) when it is imported into the Liberty dashboard.
